# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_token_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(
                choices=[('email', 'Email/Password'), ('google', 'Google')],
                default='email',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(
                blank=True,
                help_text="Google's stable unique subject ID — safer than matching on email alone.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
