# Generated by Django 4.2.26 on 2026-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general', 'General Consultation'), ('specialist', 'Specialist'), ('follow-up', 'Follow-up'), ('lab', 'Lab Test'), ('physiotherapy', 'Physiotherapy')], default='general', max_length=30)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
