# Generated by Django 6.0.7 on 2026-08-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_user_id_d4ad0a_idx',
            old_name='ai_usage_lo_user_id_8f1c3a_idx',
        ),
    ]
