# Generated by Django 4.2.26 on 2026-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Monitoring', 'Monitoring'), ('Wellness', 'Wellness'), ('Wearables', 'Wearables'), ('Relaxation', 'Relaxation'), ('Pain Relief', 'Pain Relief'), ('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Dental', 'Dental'), ('Safety', 'Safety'), ('Mobility', 'Mobility')], max_length=50)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('img', models.CharField(max_length=500)),
                ('images', models.JSONField(default=list)),
                ('has_model', models.BooleanField(default=False)),
                ('model_file', models.CharField(blank=True, max_length=500)),
                ('has_video', models.BooleanField(default=False)),
                ('video_file', models.CharField(blank=True, max_length=500)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
